AllCops:
  TargetRailsVersion: 5.2
  TargetRubyVersion: 2.5
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
    - rubocop-rspec
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'
    - 'congig/**/*'

Rails:
  Enabled: true

Style/StringLiterals:
  Exclude:
    - Gemfile
    - Gemfile.lock
  EnforcedStyle: double_quotes
  Enabled: true
