AllCops:
  TargetRailsVersion: 5.2
  TargetRubyVersion: 2.5
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
    - rubocop-rspec
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'
    - 'config/**/*'

Rails:
  Enabled: true

Style/StringLiterals:
  Exclude:
    - Gemfile
    - Gemfile.lock
  EnforcedStyle: double_quotes
  Enabled: true

# Too spammy
Style/Documentation:
  Enabled: false

# Will probably be default in ruby 3
Style/FrozenStringLiteralComment:
  Enabled: false

# Do not write 1234 as 1_234
Style/NumericLiterals:
  Enabled: false

# Don't enforce adding the filename to the file
Naming/FileName:
  Enabled: false

# This is silly
Style/SymbolArray:
  Enabled: false

# This doesn't add value.
Style/EmptyMethod:
  Enabled: false
